### ISSUE TITLE
Database Tables for Users

### ISSUE THREAD

**Issue by lukecampbell** [asascience-open/ooi-ui#100]
Create the necessary tables (see @FBRTMaka) for users and scopes.

**Comment by lukecampbell** [comment]
For reference 

![wireframe](https://rpsasa.mybalsamiq.com/projects/ooi-scienceuser/User%20Registration.jpeg?version=3&etag=7E0bS_cSch5Emy6ppEbvJ9xvkSxK6t5R)

**Comment by oceanzus** [comment]
first crack at it in the ooiui_dev_schema on RDS
