### ISSUE TITLE
Database Tables for Annotations

### ISSUE THREAD

**Issue by lukecampbell** [asascience-open/ooi-ui#108]
Kind of what I'm thinking is like

- user_id  
- created_time
- modified_time
- reference_type (table)
- reference_id
- comment
- title (32 character limit or something)

That way we can associate comments with just about anything in asset management.

**Comment by oceanzus** [comment]
What do you think reference_id contains?  It seems like there would be a references table, but I'm fuzzy on what references really needs to be.

**Comment by lukecampbell** [comment]
I'm not sure the best way to do it but it would be nice to have the ability to annotate just about anything. For delivery 3 it just has to be a stream but in the long run, if it's technically easy, I was thinking we could have a column that would identify the table that it relates to and the reference_id be the id column of the referenced table.

so like

|id|created_time|modified_time|reference_type|reference_id|title|comment|
|--|------------|-------------|--------------|------------|-----|-------|
|12|...|...|streams|1203|Instrument Removed|We removed the instrument from the bathtup to remove fouling|
|13|...|...|instrument_deploymetns|12|Initial Deployment|First time we've deployed this instrument|

**Comment by oceanzus** [comment]
will do...making it so now for discussion later today
