### ISSUE TITLE
User Management Service Connections

### ISSUE THREAD

**Issue by lukecampbell** [asascience-open/ooi-ui#98]
Work with @brian-smith723 to create the appropriate services connections to connect the user registration to the UI front-end.

![User Registration](https://rpsasa.mybalsamiq.com/projects/ooi-scienceuser/User%20Registration.jpeg?version=3&etag=7E0bS_cSch5Emy6ppEbvJ9xvkSxK6t5R)

**Comment by FBRTMaka** [comment]
endpoints can accept user registration, and user login.  very simply, but it works
